version: '3.8'

services:
  scoringkp-fe:
    build: .
    container_name: scoringkp-fe
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    expose:
      - "3000"
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
    networks:
      - scoringkp-net
    restart: always

  nginx:
    image: nginx:alpine
    container_name: scoringkp-proxy
    ports:
      - "3000:3000"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - scoringkp-fe
    networks:
      - scoringkp-net
    restart: always

networks:
  scoringkp-net:
    driver: bridge
